install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: .vuepress/dist
  keep-history: true
  on:
    branch: gh-pages  