language: node_js
node_js: 11

cache:
  directories:
    - node_modules

script:
  - chmod +x deploy.sh
  - ./deploy.sh


# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   local-dir: docs/.vuepress/dist
#   keep-history: false
#   on:
#     branch: gh-pages  